name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  autotools:
    runs-on: ${{ matrix.sets.os }}
    env:
      CC: ${{ matrix.sets.cc }}
      CXX: ${{ matrix.sets.cxx }}
      CXXFLAGS: -Og -pipe -D_DEBUG
      GTEST_SRCDIR: /usr/src/googletest
    strategy:
      fail-fast: false
      matrix:
        sets:
          - os: ubuntu-18.04
            cc: gcc-6
            cxx: g++-6
            package: g++-6

          - os: ubuntu-18.04
            cc: gcc-7
            cxx: g++-7
            package: g++-7

          - os: ubuntu-18.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8


          - os: ubuntu-18.04
            cc: clang-4.0
            cxx: clang++-4.0
            package: clang-4.0

          - os: ubuntu-18.04
            cc: clang-5.0
            cxx: clang++-5.0
            package: clang-5.0

          - os: ubuntu-18.04
            cc: clang-6.0
            cxx: clang++-6.0
            package: clang-6.0

          - os: ubuntu-18.04
            cc: clang-7
            cxx: clang++-7
            package: clang-7

          - os: ubuntu-18.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-18.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-18.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10


          - os: ubuntu-20.04
            cc: gcc-7
            cxx: g++-7
            package: g++-7

          - os: ubuntu-20.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8

          - os: ubuntu-20.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-20.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10


          - os: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-20.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-20.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10
    steps:
    - uses: actions/checkout@v2
    - name: dependencies installation
      run: |
        sudo apt update
        sudo apt install autoconf-archive libgnutls28-dev libgtest-dev libgtkmm-3.0-dev libltdl-dev libtool zlib1g-dev ${{ matrix.sets.package }}
    - name: autoreconf -i
      run: autoreconf -i
    - name: ./configure
      run: ./configure
    - name: make -j$(nproc)
      run: make -j$(nproc)
    - name: make check -j$(nproc)
      run: make check -j$(nproc)
    - name: ./src/jdim -V
      run: ./src/jdim -V

  meson:
    runs-on: ${{ matrix.sets.os }}
    env:
      CC: ${{ matrix.sets.cc }}
      CXX: ${{ matrix.sets.cxx }}
    strategy:
      fail-fast: false
      matrix:
        sets:
          - os: ubuntu-18.04
            cc: gcc-6
            cxx: g++-6
            package: g++-6

          - os: ubuntu-18.04
            cc: gcc-7
            cxx: g++-7
            package: g++-7

          - os: ubuntu-18.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8


          - os: ubuntu-18.04
            cc: clang-4.0
            cxx: clang++-4.0
            package: clang-4.0

          - os: ubuntu-18.04
            cc: clang-5.0
            cxx: clang++-5.0
            package: clang-5.0

          - os: ubuntu-18.04
            cc: clang-6.0
            cxx: clang++-6.0
            package: clang-6.0

          - os: ubuntu-18.04
            cc: clang-7
            cxx: clang++-7
            package: clang-7

          - os: ubuntu-18.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-18.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-18.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10


          - os: ubuntu-20.04
            cc: gcc-7
            cxx: g++-7
            package: g++-7

          - os: ubuntu-20.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8

          - os: ubuntu-20.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-20.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10


          - os: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-20.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-20.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: dependencies installation
      run: |
        sudo apt update
        sudo apt install libgnutls28-dev libgtest-dev libgtkmm-3.0-dev libltdl-dev libtool ninja-build zlib1g-dev ${{ matrix.sets.package }}
    - name: install meson==0.49.2
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install meson==0.49.2
    - name: meson builddir -Dbuildtype=debugoptimized -Dcpp_args="-D_DEBUG" -Dcpp_std=c++17
      run: meson builddir -Dbuildtype=debugoptimized -Dcpp_args="-D_DEBUG" -Dcpp_std=c++17
    - name: meson test -C builddir
      run: meson test -C builddir
    - name: ./builddir/src/jdim -V
      run: ./builddir/src/jdim -V
