name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  library-build-time:

    runs-on: ubuntu-18.04
    env:
      CC: gcc-7
      CXX: g++-7
      CXXFLAGS: ${{ matrix.march }}
      GTEST_SRCDIR: /usr/src/googletest
    strategy:
      matrix:
        library:
          - option:
            packages: libgnutls28-dev
          - option: --with-thread=std
            packages: libgnutls28-dev
          - option: --with-tls=openssl
            packages: libssl-dev
          - option: --with-regex=oniguruma
            packages: libgnutls28-dev libonig-dev
          - option: --with-regex=pcre
            packages: libgnutls28-dev libpcre3-dev
          - option: --with-sessionlib=no
            packages: libgnutls28-dev libpcre3-dev
          - option: --with-migemo
            packages: libgnutls28-dev libmigemo-dev
          - option: --with-alsa
            packages: libgnutls28-dev libasound2-dev
          - option: --with-xdgopen
            packages: libgnutls28-dev
          - option: --with-pangolayout
            packages: libgnutls28-dev
          - option: --with-disable-compat-cache-dir
            packages: libgnutls28-dev
        march: [-march=native, ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies installation (${{ matrix.library.packages }})
      run: |
        sudo apt update
        sudo apt install autoconf-archive libgtest-dev libgtkmm-3.0-dev libltdl-dev libtool zlib1g-dev g++-7 ${{ matrix.library.packages }}
    - name: autoreconf -i
      run: autoreconf -i
    - name: ./configure --with-gtkmm3=yes ${{ matrix.library.option }}
      run: ./configure --with-gtkmm3=yes ${{ matrix.library.option }}
    - name: make -j$(nproc)
      run: make -j$(nproc)
    - name: make check -j$(nproc)
      run: make check -j$(nproc)
    - name: ./src/jdim -V
      run: ./src/jdim -V
